spring.application.name=ecapp
spring.datasource.driver-class-name=org.postgresql.Driver
# DBで使用するURLを環境変数として設定
spring.datasource.url=${SPRING_DATASOURCE_URL}
# DBで使用するユーザーを環境変数として設定
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# DBで使用するパスワードを環境変数として設定
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}