name: CI-CD
env:
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_DBNAME: ${{ secrets.SPRING_DATASOURCE_DBNAME }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

# 実行トリガー
on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - develop
      - release
      - main
    # PRのクローズ時（マージ含む）
    types: [closed]

# 実行ジョブ
jobs:
  # 1) featureへのpush時にテスト・ビルド
  feature-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18.4
        env:
          # 作成するデータベース名
          POSTGRES_DB: $SPRING_DATASOURCE_DBNAME
          # データベースユーザー名
          POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
          # パスワード
          POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
        ports:
          - 5432:5432
        options: >-
          # ヘルスチェック
          --health-cmd pg_isready
          # チェック間隔
          --health-interval 10s
          # タイムアウト時間
          --health-timeout 5s
          # リトライ回数
          --health-retries 5
    steps:
      - name: リポジトリのコードをランナーにクローン
        uses: actions/checkout@v4

      - name: Amazon Corretto 21 をセットアップ
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          # ライブラリをキャッシュ
          cache: maven

      - name: テスト・ビルド実行
        run: cd ./ecapp/ecapp && mkdir target && mvn -B package
